name: SurvivalPlus
main: uk.codingbadgers.SurvivalPlus.SurvivalPlus
version: 1.0
authors: [thefish97, n3wton]
depends: [BukkitDatabaseManager, Vault]
softdepend: []
description: Fundamental plugins root plugin

commands:
    SurvivalPlus:
        description: Main command for the plugin
        usage: /<command> 
    modules:
        description: Lists all modules
        usage: /<command>